id: PE46A0ACE
initial_creation_type: ocr
source_metadata:
  volumes:
    5a4aa7480eb74854856bf971519c7a52:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
