id: DFF2497A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T14:01:38+00:00'
last_modified: '2022-05-29T08:16:05.772570+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d3d8:
      image_group_id: I1PD95920
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1529
      order: 75
      base_file: d3d8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
